### ISSUE TITLE
problem when uploading file larger then 20 mb

### ISSUE THREAD

**Issue by repiatx** [danielm/uploader#100]
Hi. thx for you hard work. It works great but when i upload a  rar or zip file "a.zip" or "a.rar" with the 26 MB on just one file. it gives me this error on php upload file.

> Exception has occurred. RuntimeException: Invalid parameters.
and it's not posting any $_FILE variable to php upload file.
![1](https://user-images.githubusercontent.com/48159043/62474305-449de580-b7ab-11e9-965e-d999e7ae0fc0.PNG)

and it gives me this error on my upload.html

> Bad Request
![2](https://user-images.githubusercontent.com/48159043/62474480-a6f6e600-b7ab-11e9-8841-486fd722fe24.PNG)

help me plz.

**Comment by xpressonlineventures** [comment]
Did you solve the problem?

**Comment by repiatx** [comment]
i found solutions. You have to edit` php.ini`. It was all about limit of uploading file size. it wasnt about script.
```
upload_max_filesize = 20M
post_max_size = 21M
```
to 
```
upload_max_filesize = 999999M
post_max_size = 999999M
```
