### ISSUE TITLE
Project abandoned

### ISSUE THREAD

**Issue by craigmayhew** [danielm/uploader#114]
There hasn't been a commit to this repo since 16th January 2018.

I've reached out to Daniel on twitter, and email. However, I have not heard back, and I hope he is OK.

Daniel, if you read this, thank you for open sourcing this repo. Over the years it's clearly helped a lot of folks, and I'm sure volunteers would take on the management and development if you are happy to transfer the repo to an organisation or another user. I'd be happy to volunteer for this, and/or work with others if this is something you would be happy with.

To everyone looking to submit PRs and fixes, there is no obvious candidate fork. There are 357 forks, and few of them have any stars. The forks that have new commits all appear to be attached to PRs on this repo. Forks with recent commits are visible here: https://github.com/danielm/uploader/network

**Comment by cheema14** [comment]
I was looking out for a fix but unfortunately found nothing.

**Comment by danielm** [comment]
project is not fully abandoned, many of the PR are people asking for back-end question and this is only a simple frontend jquery project. For a small project, you have no idea how many emails i got asking where the files are stored.... i need to filter and close most of the stuff sent.

Times have changed for sure..., and i will try to review most of the relevant stuff in the following weeks.

**Comment by craigmayhew** [comment]
Welcome back and thanks again @danielm !
