### ISSUE TITLE
cancel upload image

### ISSUE THREAD

**Issue by sdnaghdi** [danielm/uploader#12]
hi, thanks for your work.
Is it possible to cancel uploading file before success or error ?
thnx

**Comment by danielm** [comment]
Hey, thanks for trying the plugin!. This feature is actually implemented on the devel branch, but still some work left before it gets to master for next release. You could try it tho, at your own risk :)

**Comment by DavyLin** [comment]
I want to add the cancel uploading file  for the plugin;But i have trouble with cancel uploading.Can you tell me how to do it;

**Comment by danielm** [comment]
@DavyLin Look at my previous answer.

**Comment by danielm** [comment]
Closing the issue. For future reference, included in newest release.

**Comment by simioluwatomi** [comment]
But I just looked through the demo and there is no example of how to cancel uploads. Would you please point me in the right direction? Thanks
