### ISSUE TITLE
in your README file has a error 

### ISSUE THREAD

**Issue by bengben** [danielm/uploader#23]
onUploadProgress:

onUploadProgress: function(id, percent){
  console.log('Upload of #' + id ' is at %' + percent);
  // do something cool here!
}

it's error  

-------------------"  +  here " ----------------

onUploadProgress: function(id, percent){
  console.log('Upload of #' + id + ' is at %' + percent);
  // do something cool here!
}

**Comment by xDiglett** [comment]
Also at:

			onFallbackMode: function(message){
			  console.log('Upload plugin can\'t be initialized: ' + message);
			},
