### ISSUE TITLE
add plugin to dynamically added element

### ISSUE THREAD

**Issue by dellert** [danielm/uploader#24]
How can I add yours plugin to dynamically added elements on page?
thanks

**Comment by dellert** [comment]
found a solution

**Comment by kirschbaumj** [comment]
Hello,

I am also having problems using this on DOM elements that get dynamically to the page (Vue.js in my case). It seems to be the on drop and on change events in the init method. I was able to get this working locally by changing the jquery selector to 

`$(document).on('drop', widget.element, function(evt){`

and 

`$(document).on('change', widget.element.find('input[type=file]'), function(evt){`

on lines 109 and 117 of the full/non-minified version of the plugin. Could this be looked into?

Thanks!
