### ISSUE TITLE
Upload to my desire path

### ISSUE THREAD

**Issue by abdullah-zudioz** [danielm/uploader#27]
Hi,
Thank you for this plugin awesome.

I set <b>url: upload.php</b> now what to do then? how to upload the images to the desired path.
Can you give me sample <b>upload.php</b>

Please help me.

Thank You

**Comment by danielm** [comment]
Closing the issue. The plugin only provides Frontend logic, for backend there is now a simple upload.php on the demo folder.

However, this is a really simple , no validation or any kind of security check. ONLY use it for testing, or just as a start point.

**Comment by ghost** [comment]
@danielm 
would you consider adding a secure php backend? I like the look and feel of this library
