### ISSUE TITLE
Uncaught ReferenceError: Modernizr is not defined

### ISSUE THREAD

**Issue by Thorium** [danielm/uploader#30]
This assumes that Modernizr is defined (Modernizr.touch) and if not, this will throw exception...
Is Modernizr needed?

Also demo-preview.js under demos is so generic that it could be located in src-folder...

Others than that, looks very nice, thanks!

**Comment by danielm** [comment]
Closing the issue. This was a very weird issue that i was never able to reproduce. My guess is that it should be fixed on the newest (big) release
