### ISSUE TITLE
Modify script to upload .torrent files?

### ISSUE THREAD

**Issue by droidzone** [danielm/uploader#34]
I'm having trouble modifying the script to upload .torrent files.
I tried:

```
allowedTypes: '^.*\.(torrent)$',
```

And:

```
allowedTypes: 'application/x-bittorrent',
```

Also referenced it at http://stackoverflow.com/questions/32675064/matching-file-type-match

**Comment by danielm** [comment]
Closing the issue. But for future reference:

Case 1: To validate an extension should be using
```javascript
extFilter: ['torrent']
```

Case 2: Probably the regex is wrong.
