### ISSUE TITLE
Upload files on submit?

### ISSUE THREAD

**Issue by ekv88** [danielm/uploader#41]
Is it possible to change plugin to upload files on form submit?

**Comment by samfrjn11** [comment]
You can alter some lines in the DmUploader.prototype.init function.

**Comment by laravelish** [comment]
anyone help

**Comment by debasispanda** [comment]
This plugin works for the ondrop event for the container and onchange event for the input[type="file"]. Check in the source file (dmuploader.js)

``` javascript
   widget.element.on('drop', function (evt){
      evt.preventDefault();
      var files = evt.originalEvent.dataTransfer.files;

      widget.queueFiles(files);
    });

    //-- Optional File input to make a clickable area
    widget.element.find('input[type=file]').on('change', function(evt){
      var files = evt.target.files;

      widget.queueFiles(files);

      $(this).val('');
    });
```

So same function you can call for the onsubmit event for the form. 

Hope this works fine for you.

**Comment by florencioq** [comment]
The problem of using the ondrop event is that I can not access the name of the file that I am going to upload, because the HTML INPUT does not update the HTML page with the name of the file, and after the upload, remains the message "No file selected" in the HTML page, what is confusing for the user.

**Comment by gficher** [comment]
@florencioq I recommend you to hide the input and use a button instead.

For instance: [
![image](https://user-images.githubusercontent.com/4522115/28649009-34f5ae2e-7248-11e7-9f9a-29f18f5ff55d.png)
](url)
