### ISSUE TITLE
any method for stop/destroy/clear queue ?

### ISSUE THREAD

**Issue by leafiy** [danielm/uploader#44]

**Comment by gficher** [comment]
This is supported in _devel_ branch but with some limitations so I decided to modify the code to add a callback method.

Here you go [https://gist.github.com/gficher/27a77b5040cf32d7ab92c9ccfcd5d5aa](url)

**How to use it?**
Good question.

The plugin calls _onUploadCancel_ when a upload is aborted.

**How do I abort it then?**
Another good question.

You should use your drag-and-drop element like this:
```
$('#drag-and-drop-zone').dmUploader('cancel', id);
```

The ID is a number and not the row ID, so use a integer (from 0 to _n_)

**But how can I get the ID?**
You are full of good questions!

Just add a button to your file row and bind an event to it

```
$('#upload-status-panel tbody').on('click', '.btn-cancel', function() {
    // Gets id from row attribute
    var id = $(this).closest('tr').attr('data-id');
    // Aborts upload
    $('#drag-and-drop-zone').dmUploader('cancel', id);
});
```


**Where did _data-id_ come from?**

To get thinks easier, add this attr to the file row like this:
![image](https://user-images.githubusercontent.com/4522115/28649412-1517447a-724b-11e7-8b8b-095d01dcf195.png)

**Comment by danielm** [comment]
Closing the issue. Newest release includes this.

The difference of what was originally on the devel branch is:

```javascript
$('#drag-and-drop-zone').dmUploader('cancel', id);
```

or to do it 'globally', use it without a file ID:

```javascript
$('#drag-and-drop-zone').dmUploader('cancel');
```

More info on the Readme.md, or the online demos.

https://danielmg.org/demo/java-script/uploader/controls
