### ISSUE TITLE
Cursor remains in "loading" state

### ISSUE THREAD

**Issue by umdieecke** [danielm/uploader#45]
dmuploader all works fine, thanks for that!

The only issue i am confronted with is that the cursor won't go back to its normal (default) state when the upload is finished. (Occurs only in Opera)
Does anyone have a quick fix for that?

**Comment by samfrjn11** [comment]
As far as I can see the script doesn't change the cursor, so I guess it's a bug in Opera?
However, to fix your problem you can just add something like `$('body').css('cursor', 'default');` in your own script (see callback onComplete) or in the dmuploader.js script in the ajax request under the complete function (+- line 171)
