### ISSUE TITLE
Image exif Orientation, When uploading by android device 

### ISSUE THREAD

**Issue by anpdev** [danielm/uploader#50]
Hi danielm, 
 Your work is super, any I really like this plugin, but I recently experienced an issue on android device.
 when image uploaded it get rotate at 90 degree angle or different possibility. Is the any method to get rid of this situation. 

thanks

**Comment by blenderdeluxe** [comment]
Hi @anpdev I think that you resolve this yet haha for the time but for other person maybe this is interesting, I apply all exif orientation with php code in my case using [Intervention Image](http://image.intervention.io/) package You can see the pull that I made time ago in the url [https://github.com/UniSharp/laravel-filemanager/pull/143](https://github.com/UniSharp/laravel-filemanager/pull/143)

I use ->orientate()
the code is 

//Apply orientation from exif data
$img = Image::make($file->getRealPath())->orientate();
$upload = $img->save($dest_path . $new_filename, 90);

Regards!

**Comment by danielm** [comment]
This seems more like a backend thing to do.

Said that and thanks to the File and Blob API it may be something  doable, but it's probably way out of reach for what's the plugin is right know.

May be a good exercise to add it to our images demos imo: https://danielmg.org/demo/java-script/uploader/images

Closing the issue for now,
