### ISSUE TITLE
upload goes on if onBeforeUpload returns false

### ISSUE THREAD

**Issue by talal424** [danielm/uploader#51]
the minified file doesn't return if onBeforeUpload returns false

these lines are forgotten in the minified version

``` javascript
var can_continue = widget.settings.onBeforeUpload.call(widget.element, widget.queuePos);
    
    // If the client function doesn't return FALSE then continue
    if( false === can_continue ) {
      return;
    }
```

**Comment by danielm** [comment]
Closing the issue. For future reference:

Yes this feature was only on git for testing and it was broken and was not finished.

Now this is available using the `onNewFile` callback, by returning false the file will be completely ignored by the plugin.
