### ISSUE TITLE
Files not uploading

### ISSUE THREAD

**Issue by wkaminski** [danielm/uploader#56]
Hi,

I am using uploader installed with npm. Uploader gets initiated properly (onInit callback fires). When I choose file - onNewFile callback fires. But nothing else gets fired. File is not being uploaded. No errors (I hooked all possible callbacks) and file not getting sent :/

In different project, where I use uploader installed manually by including .js files - it's working great.

Any ideas what I am doing wrong? :(
https://pastebin.com/UqqY1CwC

**Comment by wkaminski** [comment]
When I use dmUploader 0.1 manually (importing .js file) - it's working fine.

**Comment by timoleon** [comment]
worry , I am on holiday abroad. don't have any idea.

**Comment by danielm** [comment]
Hey,

The code you provided seems aright , I haven't used a fresh install using npm in a while, but I have gotten a few reports from people having swim issues from using the minified version which  may be the case here.
The project is getting a little love the next couple days so until then I won't be able to update it

**Comment by wkaminski** [comment]
@danielm ok, no worries. I am using manual .js files for now. I will check npm version in few days.

Thanks! ;)

**Comment by danielm** [comment]
Closing the issue.

With the newest release the plugin can be installed directly from NPM using the oficial package:

`npm install dm-file-uploader` --save
