### ISSUE TITLE
How to update parent div after 'onComplete'?

### ISSUE THREAD

**Issue by nobutsta** [danielm/uploader#64]
I have `dataTable` with ajax content in the parent page. And I upload file with uploader. Then I need to update the table once the upload is complete. So I call with : 

```
    onComplete: function(){
      $(body).find('#pflTable').ajax.reload();//update ajax table
    },
```

But the script error because 'body is not defined'. Please be advised!

**Comment by danielm** [comment]
Thats more like a JS syntax error heh. Using JQuery you should use something like $('body')
