### ISSUE TITLE
It'd be great if 'id' can be sent as a part of extradata

### ISSUE THREAD

**Issue by abbasl7** [danielm/uploader#67]
While uploading the file, if 'id' can also be sent in the request along with file, it would be handy to deal with some situations where we use that as a unique identifier for each file.

**Comment by dcaton** [comment]
Turns out this is easy.   If you specify a function for the extraData option, a single parameter is passed in which is the file id.

```
        extraData: function (fileid)
        {
            return {
                "fileid": fileid
            };
        },
```

 You'll end up with a form field named "fileid" in your HTTP request that contains the id.

**Comment by abbasl7** [comment]
That's smart! Thanks, @dcaton 👍
