### ISSUE TITLE
File List does not look accurate with lots of files being uploaded

### ISSUE THREAD

**Issue by Bijan-A** [danielm/uploader#85]
When I am adding a lot of files, the spacing starts to look very off.

To see an example of this, go to the [Basic Demo](https://danielmg.org/demo/java-script/uploader/basic) and then in console run `ui_multi_add_file('xxx','xxx')` around 5+ times just to add these examples. You will see the CSS starts looking a little borked.

Here is a screenshot when I try to add 10 files.

![image](https://user-images.githubusercontent.com/116760/47881598-d7a48c00-dde3-11e8-841d-ffc5d0af4357.png)

I tested on Chrome, Firefox, and Edge and this only seems to be a problem on Chrome. Can anyone else verify?

**Comment by SapientHetero** [comment]
I saw the same thing. Changed the .css for the file list to remove flex classes, IIRC.

**Comment by Bijan-A** [comment]
> I saw the same thing. Changed the .css for the file list to remove flex classes, IIRC.

I do not see any flex classes in the `jquery.dm-uploader.min.css` or `styles.css` files

**Comment by SapientHetero** [comment]
They're inherited from bootstrap. Use chrome developer tools to look at
styles.

**Comment by SapientHetero** [comment]
Here are your culprits. -webkit-box-flex and flex. Turn 'em off and you're good to go
It's been awhile, but I believe I fixed this using the following .css to override the @media css in grids.css. Make sure it is loaded AFTER your bootstrap css.

```

[class*="col-"] {
	padding-top: 1rem;
	padding-bottom: 1rem;
}   
hr {
	margin-top: 2rem;
	margin-bottom: 2rem;
}
#files {
    overflow-y: scroll !important;
    min-height: 320px;
}
@media (min-width: 768px) {
	#files {
		min-height: 300;
	}
}
```
![image](https://user-images.githubusercontent.com/39421987/47971463-c23b9600-e05f-11e8-82c6-8cca33481ebc.png).

**Comment by SapientHetero** [comment]
Now it looks like this: ![image](https://user-images.githubusercontent.com/39421987/47971463-c23b9600-e05f-11e8-82c6-8cca33481ebc.png). 

I also had to tweak the scrolling script to force the currently-uploading file to be visible at all times. It looks like this:
```
function scrollToView(element, parent) {
    element = $(element);
    parent = $(parent);

    var tMarg = parseInt(element.css("margin-top"));
    var bMarg = parseInt(element.css("margin-bottom"));
    var height = element.innerHeight() + tMarg + bMarg;
    var offset = element.position().top;
    var offset_end = element.position().top + height;
    var visible_area_start = parent.scrollTop();
    var visible_area_size = parent.innerHeight();

    //console.log("offset=",offset,"visible_area_start=",visible_area_start,"offset_end=",offset_end,"visible_area_size=",visible_area_size);

    if (offset < 0) {
        parent.animate({scrollTop: offset}, 50);
        return false;
    } else if (offset_end > visible_area_size) {
        parent.animate({scrollTop: parent.scrollTop() + height}, 50);
        return false;
    }

    return true;
}
```
